### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by peif1987** [hzha559/vehicle-recognition-resnet152#1]
Hi, I see you use Vehicle-1M dataset,
Could you please share it?

**Comment by hzha559** [comment]
Hi,
Please apply for the database with this link. http://www.nlpr.ia.ac.cn/iva/homepage/jqwang/Vehicle1M.htm
It is illegal for me to redistribute it.

**Comment by peif1987** [comment]
Thanks，I will try it.
